bundle_name: publish
description: null
version: 0.0.1
image: null
libraries: null
system_dependencies: null
environment: null
commands: null
blocks:
- name: Read_Images
  file_name: blocks
  class_name: Input_Block
  label: Read_Images
  description: ''
  tags: []
  libraries: []
  executors:
    name: ProcessExecutor
  inputs: []
  outputs: []
  defaultExecutionMode: ProcessExecutor
  source:
    module_name: publish
category: cat1
